version: "3"
services:
  db:
    image: postgres:16.2
    env_file:
      - .env
    networks:
      - default
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
